# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetable',
            name='task',
            field=models.CharField(default='Init', max_length=255, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='basetable',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
